import type { GitHubProfileBundle } from "@/lib/types";

const owner = { login: "proof-dev" };

export const demoProfileBundle: GitHubProfileBundle = {
  user: {
    login: "proof-dev",
    id: 100001,
    avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
    html_url: "https://github.com/proof-dev",
    name: "Avery Proof",
    company: "Open Source Studio",
    blog: "https://example.com",
    location: "Remote",
    bio: "Full-stack engineer building TypeScript tools, data products, and developer workflows.",
    public_repos: 8,
    followers: 248,
    following: 42,
    created_at: "2018-03-14T10:00:00Z",
    updated_at: "2026-06-20T12:00:00Z"
  },
  repos: [
    {
      id: 1,
      name: "proof-board",
      full_name: "proof-dev/proof-board",
      html_url: "https://github.com/proof-dev/proof-board",
      description: "Evidence dashboard for reviewing portfolio signals.",
      fork: false,
      archived: false,
      homepage: "https://example.com/proof-board",
      language: "TypeScript",
      stargazers_count: 38,
      forks_count: 6,
      open_issues_count: 3,
      size: 1840,
      created_at: "2025-09-04T08:00:00Z",
      updated_at: "2026-06-21T08:00:00Z",
      pushed_at: "2026-06-21T08:00:00Z",
      topics: ["typescript", "nextjs", "analytics"],
      owner
    },
    {
      id: 2,
      name: "repo-health-cli",
      full_name: "proof-dev/repo-health-cli",
      html_url: "https://github.com/proof-dev/repo-health-cli",
      description: "CLI for auditing README coverage and repository metadata.",
      fork: false,
      archived: false,
      homepage: null,
      language: "TypeScript",
      stargazers_count: 21,
      forks_count: 2,
      open_issues_count: 1,
      size: 920,
      created_at: "2025-05-12T08:00:00Z",
      updated_at: "2026-05-18T08:00:00Z",
      pushed_at: "2026-05-18T08:00:00Z",
      topics: ["cli", "github-api"],
      owner
    },
    {
      id: 3,
      name: "event-trace",
      full_name: "proof-dev/event-trace",
      html_url: "https://github.com/proof-dev/event-trace",
      description: "Public event timeline visualizer.",
      fork: false,
      archived: false,
      homepage: "https://example.com/event-trace",
      language: "Python",
      stargazers_count: 12,
      forks_count: 1,
      open_issues_count: 0,
      size: 640,
      created_at: "2024-11-02T08:00:00Z",
      updated_at: "2026-04-11T08:00:00Z",
      pushed_at: "2026-04-11T08:00:00Z",
      topics: ["python", "data-viz"],
      owner
    },
    {
      id: 4,
      name: "starter-next-dashboard",
      full_name: "proof-dev/starter-next-dashboard",
      html_url: "https://github.com/proof-dev/starter-next-dashboard",
      description: "Forked dashboard starter used for experiments.",
      fork: true,
      archived: false,
      homepage: null,
      language: "TypeScript",
      stargazers_count: 4,
      forks_count: 0,
      open_issues_count: 0,
      size: 300,
      created_at: "2024-02-08T08:00:00Z",
      updated_at: "2025-01-15T08:00:00Z",
      pushed_at: "2025-01-15T08:00:00Z",
      topics: ["starter"],
      owner
    },
    {
      id: 5,
      name: "tiny-css-notes",
      full_name: "proof-dev/tiny-css-notes",
      html_url: "https://github.com/proof-dev/tiny-css-notes",
      description: null,
      fork: false,
      archived: false,
      homepage: null,
      language: "CSS",
      stargazers_count: 0,
      forks_count: 0,
      open_issues_count: 0,
      size: 24,
      created_at: "2023-01-02T08:00:00Z",
      updated_at: "2023-01-03T08:00:00Z",
      pushed_at: "2023-01-03T08:00:00Z",
      topics: [],
      owner
    },
    {
      id: 6,
      name: "legacy-jquery-widget",
      full_name: "proof-dev/legacy-jquery-widget",
      html_url: "https://github.com/proof-dev/legacy-jquery-widget",
      description: "Older UI widget kept for reference.",
      fork: false,
      archived: true,
      homepage: null,
      language: "JavaScript",
      stargazers_count: 2,
      forks_count: 1,
      open_issues_count: 4,
      size: 210,
      created_at: "2020-08-02T08:00:00Z",
      updated_at: "2021-02-12T08:00:00Z",
      pushed_at: "2021-02-12T08:00:00Z",
      topics: ["legacy"],
      owner
    }
  ],
  readmeMap: {
    "proof-dev/proof-board": true,
    "proof-dev/repo-health-cli": true,
    "proof-dev/event-trace": true,
    "proof-dev/starter-next-dashboard": true,
    "proof-dev/tiny-css-notes": false,
    "proof-dev/legacy-jquery-widget": false
  },
  languageDetails: {
    "proof-dev/proof-board": { TypeScript: 220000, CSS: 36000 },
    "proof-dev/repo-health-cli": { TypeScript: 118000 },
    "proof-dev/event-trace": { Python: 82000, HTML: 9000 },
    "proof-dev/starter-next-dashboard": { TypeScript: 45000, CSS: 14000 },
    "proof-dev/tiny-css-notes": { CSS: 3000 },
    "proof-dev/legacy-jquery-widget": { JavaScript: 24000 }
  },
  events: [
    { id: "1", type: "PushEvent", created_at: "2026-06-21T08:00:00Z", repo: { name: "proof-dev/proof-board", url: "" }, payload: { commits: [{ sha: "a", message: "Improve report copy" }] } },
    { id: "2", type: "PullRequestEvent", created_at: "2026-06-18T08:00:00Z", repo: { name: "proof-dev/repo-health-cli", url: "" }, payload: { action: "opened" } },
    { id: "3", type: "IssuesEvent", created_at: "2026-06-12T08:00:00Z", repo: { name: "proof-dev/proof-board", url: "" }, payload: { action: "closed" } },
    { id: "4", type: "CreateEvent", created_at: "2026-05-30T08:00:00Z", repo: { name: "proof-dev/event-trace", url: "" }, payload: { ref_type: "branch" } },
    { id: "5", type: "WatchEvent", created_at: "2026-05-19T08:00:00Z", repo: { name: "vercel/next.js", url: "" }, payload: {} }
  ]
};
